### ISSUE TITLE
A Dependent library needs to upgrade to the latest tools.namespace

### ISSUE THREAD

**Issue by twashing** [Datomic/day-of-datomic#8]
I just cloned the latest code from github (commit a60b703c031ee13e1877ff46d125a7dc6cd25ee7, Mon Jul 1 2013). Running `lein repl` or `lein trampoline repl`. Gave me the below error. It looks like one of the dependant libraries, nrepl-inspect, is using an older version of tools.namespace (0.2.3). 

```
webkell@ubuntu:~/Projects/trial/day-of-datomic$ lein trampoline repl
:repositories detected in user-level profiles! [:user] 
See https://github.com/technomancy/leiningen/wiki/Repeatability
Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/tools/namespace/find__init.class or clojure/tools/namespace/find.clj on classpath: 
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5018.invoke(core.clj:5530)
        at clojure.core$load.doInvoke(core.clj:5529)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
```

In the Day-Of-Datomic project configuration, I put in the latest (`[org.clojure/tools.namespace "0.2.4"]`), and the repl now comes up. I'd make a pull request, but the problem seems to be in a dependent library. So ideally, the change would be made there. But Let me know if you'd like me to fix and make a pull request. 

Hth

**Comment by benkamphaus** [comment]
Hi @twashing -- thanks for reporting this issue. It no longer seems to be present in the latest version of the code. -B

**Comment by twashing** [comment]
Sweet. Thanks Ben.
